export type Subject = 
  | "Mathematics"
  | "Physics"
  | "Chemistry"
  | "Computer Science"
  | "Data Structures"
  | "Algorithms"
  | "Database Systems"
  | "Operating Systems"
  | "Networks"
  | "Software Engineering"
  | "Web Development"
  | "Machine Learning"
  | "Other";

export type Semester = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8";

export type Difficulty = "Easy" | "Medium" | "Hard";

export type ExamType = 
  | "Midterm"
  | "Final"
  | "Quiz"
  | "Assignment"
  | "Lab"
  | "Project"
  | "Other";

export interface Note {
  id: string;
  title: string;
  description?: string;
  fileUrl: string;
  fileName: string;
  fileSize: number;
  fileType: string;
  uploaderId: string;
  uploaderName?: string; // Optional for anonymous uploads
  isAnonymous: boolean;
  subject: Subject;
  semester: Semester;
  difficulty: Difficulty;
  examType: ExamType;
  professor?: string;
  tags: string[];
  averageRating: number;
  totalRatings: number;
  downloads: number;
  views: number;
  hasTopperBadge: boolean; // CGPA-based badge
  uploaderCGPA?: number; // For badge calculation
  aiSummary?: string; // Auto-generated by Gemini
  keyTopics?: string[]; // Extracted by Gemini
  extractedText?: string; // Extracted text from the document (for Q&A)
  createdAt: any;
  updatedAt: any;
}

export interface NoteRating {
  id: string;
  noteId: string;
  userId: string;
  rating: number; // 1-5
  comment?: string;
  createdAt: any;
}

export interface ExamSurvivalKit {
  id: string;
  name: string;
  description: string;
  creatorId: string;
  noteIds: string[]; // Array of note IDs
  subject: Subject;
  semester: Semester;
  examType: ExamType;
  downloads: number;
  createdAt: any;
  updatedAt: any;
}

export interface NoteFilter {
  subject?: Subject;
  semester?: Semester;
  difficulty?: Difficulty;
  examType?: ExamType;
  professor?: string;
  hasTopperBadge?: boolean;
  minRating?: number;
  searchQuery?: string;
}
